### PR TITLE
Updates to README to reflect new name and Apache

### PR DESCRIPTION
**Pull request by lbustelo**

### CODE REVIEW

**Comment by lbustelo** [comment]
@Lull3rSkat3r Please review.

**Comment by lbustelo** [comment]
@Lull3rSkat3r One more time please... and then I'll merge

**Comment by Lull3rSkat3r** [comment]
LGTM

**Comment by lbustelo** [comment]
Merged

I squashed into bbece2db0d99426392fa1e37c5a22da1f47e08b7 on master

**Pull request closed without merging**
